# Generated by Django 4.1.3 on 2022-11-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("did_citizen_win", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("nickname", models.CharField(max_length=64)),
                ("bio", models.TextField(blank=True, null=True)),
                ("leagues", models.ManyToManyField(to="leagues.league")),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did_win", models.BooleanField()),
                ("win_score", models.IntegerField(default=0)),
                ("extra_score", models.IntegerField(default=0)),
                ("player_position", models.IntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "player_role",
                    models.CharField(
                        choices=[
                            ("Citizen", "Citizen"),
                            ("Sheriff", "Sheriff"),
                            ("Mafia", "Mafia"),
                            ("Don", "Don"),
                        ],
                        default="Citizen",
                        max_length=16,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leagues.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leagues.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="leagues.league"
            ),
        ),
    ]
